variable "project" {}
variable "region" {}
variable "machine_type" {}
variable "zone" {}
variable "image" {}
variable "k8s_master_instance_name" {}
variable "k8s_master_private_ip" {}
variable "passwd" {}
variable "ansible_path" {}
variable "gce_ssh_user" {}
variable "gce_ssh_pub_key_file" {}
