---
- hosts: k8sworkers
  gather_facts: False
  vars_files:
  - /test-terraform/terraform-k8s-gcp/ansible_playbook/group_vars/env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ path }}/{{ token_file }} dest=/tmp/join_token

  - name: Joining worker nodes with kubernetes master
    shell: |
     kubeadm reset -f
     cat /tmp/join_token | tail -2 > out.sh
     sh out.sh
