--- 
- 
  hosts: all
  gather_facts: False

  tasks: 

    - name: "Update Docker repo"
      shell: |
        yum -y update
        yum -y install yum-utils
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum -y update

    - name: "Install Docker and Kubernetes"
      yum:
        name: "{{ packages }}"
        state: present
        disable_excludes: kubernetes

    - name: "Starting and Enabling the required services"
      service: 
        enabled: true
        name: "{{ item }}"
        state: started
      with_items: "{{ services }}"

    - name: "Creating Kubernetes config file"
      file: 
        path: /etc/sysctl.d/k8s.conf
        state: touch

    - name: "Configure Kubernetes config file."
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1

    - name: "Load system services"
      shell: sysctl --system

    - name: "Enabling ip4 forwarding"
      shell: "echo '1' > /proc/sys/net/ipv4/ip_forward"

  vars_files: 
    - /terraform/terraform-k8s-gce-hdfs/ansible_playbook/group_vars/env_variables
